ktor:
    application:
        modules:
            - com.iridium.ApplicationKt.module
    deployment:
        port: 8081

storages:
    - # if you are using MySQL db
    - driverClassName: "com.mysql.cj.jdbc.Driver"
      jdbcURL: "jdbc:mysql://localhost:3306/db_name_here?user=db_username_here&password=db_password_here"

    #if you are using Postgres db
    - driverClassName: "org.postgresql.Driver"
      jdbcURL: "jdbc:postgresql://localhost:5432/db_name_here?user=db_username_here&password=db_password_here"
